### ISSUE TITLE
tsv files

### ISSUE THREAD

**Issue by Shimaa1** [carrySteve/ActionRecognition#1]
Hi , thanks for releasing  the code. How can I get the tsv files, please. Could you send it to my email please?

**Comment by carrySteve** [comment]
Hi, thanks for opening this issue. But I am afraid that I cannot send you the total tsv files as they are around 400GB. If you are still interested in these files, could you please follow this [file](https://github.com/carrySteve/ActionRecognition/blob/master/Graph-Convolutional-Networks/data/write_bboxes.py) and make these TSV files by yourself?

In fact, it's not necessary to read images from TSV files, and it can take hours to make these TSV files. So, it's recommended to follow this [repo](https://github.com/Shimaa1/Group-Activity-Recognition) and read the JPEG files directly.

**Comment by Shimaa1** [comment]
Thanks for the quick reply.

**Comment by Shimaa1** [comment]
IOError: [Errno 2] No such file or directory: '../vgg/vgg_models/checkpoint_ex_119.pth'

How can I download it, please?

**Comment by carrySteve** [comment]
Sorry for the late reply. The above file is a file containing trained weights. But unluckily, as the file is written almost 2 years ago, I am afraid that the weight file is not available now.

Thanks for your interest, but pretty sorry that some of the files are incomplete. Could you please train the model by yourself if it's convenient for you?
