### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../vgg/vgg_models/checkpoint_ex_119.pth'

### ISSUE THREAD

**Issue by Shimaa1** [carrySteve/ActionRecognition#2]
Where can I download this file?

You should probably note it in the README, thanks.

**Comment by carrySteve** [comment]
Sorry for the late reply. The above file is a file containing trained weights. But unluckily, as the file is written almost 2 years ago, I am afraid that the weight file is not available now. 

Thanks for your interest, but pretty sorry that some of the files are incomplete. Could you please train the model by yourself if it's convenient for you?

**Comment by Shimaa1** [comment]
Ok, thanks for reply

**Comment by Shimaa1** [comment]
Could you please describe how to run your code in this files i.e which files for the perprocessing, training ,testing files,etc. I think that will help, thanks.

**Comment by carrySteve** [comment]
Sorry to bother, but I think readme file illustrates what every single file does. So please run the training files as other normal python files.

**Comment by Shimaa1** [comment]
Okay, I’ll try to understand it more, thanks.



On May 12, 2020, at 2:53 AM, carrySteve <notifications@github.com> wrote:

﻿

Sorry to bother, but I think readme file illustrates what every single file does. So please run the training files as other normal python files.

**Comment by Shimaa1** [comment]
Sorry for bothering, Is the checkpoint_ex_119.pth and the vgg19_bn': 'https://download.pytorch.org/models/vgg19_bn-c79401a0.pth are same, I mean should I replace the above weights with this vgg weights.
